name: Flathub Publish

on:
  schedule:
    - cron:  '0 0 * * *'  
  workflow_dispatch:

jobs:
  Build Latest Flathub Package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get Latest Commit ID
        run: |
          git clone https://github.com/squentin/gmusicbrowser.git
          cd gmusicbrowser
          LATEST_COMMIT=$(git log -n1 --format=format:"%H")
          echo $LATEST_COMMIT
          cd ../

      - name: Update Flathub Metadata
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          ls

      - name: Build Flathub Package
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          ls

