name: Flathub Publish

on:
  schedule:
    - cron:  '0 0 * * *'  
  workflow_dispatch:

jobs:
  build-daily-flathub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get Latest Commit ID
        run: |          
          LATEST_COMMIT=$(git ls-remote --heads https://github.com/squentin/gmusicbrowser.git | head -n 1 |  head -c 40)
          echo $LATEST_COMMIT

      - name: Get Escaped Date
        run: |          
          DATE="\\\"$(date +"%Y-%m-%d")\\\""
          echo $DATE

      - name: Update Flathub Metadata
        run: |
          
          sed -i "s/\"commit\": \"\(.*\)\"/\"commit\": \"$LATEST_COMMIT\"/g" org.gmusicbrowser.gmusicbrowser.json
          echo test, and deploy your project.
          ls

      - name: Build Flathub Package
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          ls

