name: Flathub Publish

on:
  schedule:
    - cron:  '0 0 * * *'  
  workflow_dispatch:

jobs:
  Build Latest Flathub Package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get Latest Commit ID
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          ls

      - name: Update Flathub Metadata
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          ls

      - name: Build Flathub Package
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          ls

